import { CliUx } from "@oclif/core"

import Base from "./base"

export default class Events extends Base<typeof Events.flags> {

  static description = "Ingest Events"

  static flags = {
    ...Base.flags,
  };

  async run(): Promise<void> {
    CliUx.ux.action.start("Starting to ingest events.. 🔮 ")

    const shipping_payload = {
      text: "This is event was generated by simo",
      title: "Investigating shipping information",
      alert_type: "info",
      tags: "service:shipping"
    }

    const inventory_payload = {
      text: "This is event was generated by simo",
      title: "Checking current inventory",
      alert_type: "info",
      tags: "service:shipping"
    }

    this.ingestPerApi("https://api.datadoghq.com/api/v1/events", JSON.stringify(shipping_payload))
    this.ingestPerApi("https://api.datadoghq.com/api/v1/events", JSON.stringify(inventory_payload))
  }

}
